### PR TITLE
fixed toggleChildren method doesn't render css correctly

### PR DESCRIPTION
**Pull request by softage0**
Since `toggleChildren` doesn't pass `parentField` to `hasChildren` method, className is not decided correctly.

It fixed by passing `parentField` to `hasChildren` method.

### CODE REVIEW

**Comment by softage0** [comment]
oh only `toggle-children.js` test is missed :(

It looks I need to add test case first lol

**Comment by bebraw** [comment]
Yeah, good after a test case.

**Comment by softage0** [comment]
Test cases has been added.
This PR also fixes Issue #3.

**Comment by bebraw** [comment]
Published as 3.0. Thanks. 👍

**Comment by softage0** [comment]
Cool!

It's little late to say that, but thanks for your work `reactabular` that includes all features what I need from React-based table :)

**Comment by bebraw** [comment]
No probs. Note that I changed the index treatment of toggling to match the old behavior so you may have to write a callback. 👍

**Pull request merged**
